version: 2.1

executors:
  kernel-builder:
    docker:
      - image: ubuntu:22.04
    resource_class: large

jobs:
  build:
    executor: kernel-builder
    steps:
      - run:
          name: Install base dependencies
          command: |
            apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            git ssh bc bison build-essential flex libssl-dev libelf-dev \
            python3 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            wget curl lld zstd cpio zip ca-certificates default-jre-headless

      - checkout

      - run:
          name: Build Kernel
          command: |
            chmod +x build.sh
            ./build.sh

      - store_artifacts:
          path: kernel-src/out-zip
          destination: KERNEL-BUILDS

workflows:
  kernel-workflow:
    jobs:
      - build
